<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="Manage.aspx.cs" Inherits="Admin_Manage" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" Runat="Server">
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-3">

                <asp:RadioButtonList AutoPostBack="true" OnSelectedIndexChanged="RadioButtonList1_SelectedIndexChanged" ID="RadioButtonList1" runat="server">
                    <asp:ListItem>Clientes</asp:ListItem>
                    <asp:ListItem>Voluntários</asp:ListItem>
                    <asp:ListItem>Idosos</asp:ListItem>
                </asp:RadioButtonList>

            </div>
            <div class="col-md-9">
                <asp:GridView ID="gvC" DataKeyNames="IDCliente" Visible="false" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" runat="server" AutoGenerateColumns="False" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellPadding="4" CellSpacing="2" ForeColor="Black" DataSourceID="SqlDataSource1">
                    <Columns>
                        <asp:BoundField DataField="Nome" HeaderText="Nome" SortExpression="Nome"></asp:BoundField>
                        <asp:BoundField DataField="Morada" HeaderText="Morada" SortExpression="Morada"></asp:BoundField>
                        <asp:BoundField DataField="DataNasc" HeaderText="DataNasc" SortExpression="DataNasc"></asp:BoundField>
                        <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email"></asp:BoundField>
                        <asp:BoundField DataField="Contactos" HeaderText="Contactos" SortExpression="Contactos"></asp:BoundField>
                        <asp:BoundField DataField="Username" HeaderText="Username" SortExpression="Username"></asp:BoundField>
                    </Columns>
                    <FooterStyle BackColor="#CCCCCC"></FooterStyle>

                    <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White"></HeaderStyle>

                    <PagerStyle HorizontalAlign="Left" BackColor="#CCCCCC" ForeColor="Black"></PagerStyle>

                    <RowStyle BackColor="White"></RowStyle>

                    <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White"></SelectedRowStyle>

                    <SortedAscendingCellStyle BackColor="#F1F1F1"></SortedAscendingCellStyle>

                    <SortedAscendingHeaderStyle BackColor="#808080"></SortedAscendingHeaderStyle>

                    <SortedDescendingCellStyle BackColor="#CAC9C9"></SortedDescendingCellStyle>

                    <SortedDescendingHeaderStyle BackColor="#383838"></SortedDescendingHeaderStyle>
                </asp:GridView>
                
                <asp:SqlDataSource DeleteCommand="DELETE FROM Cliente WHERE IDCliente=@IDCliente" UpdateCommand="UPDATE Cliente SET Nome=@Nome, Morada=@Morada, DataNasc=@DataNasc, Email=@Email, Contactos=@Contactos WHERE IDCliente=@IDCliente" runat="server" ID="SqlDataSource1" ConnectionString='<%$ ConnectionStrings:ConnectionString %>' SelectCommand="SELECT [IDCliente], [Nome], [Morada], [DataNasc], [Email], [Contactos], [Username] FROM [Cliente]"></asp:SqlDataSource>
                <asp:GridView ID="gvV" DataKeyNames="IDVoluntario" Visible="false" runat="server" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" AutoGenerateColumns="False" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellPadding="4" CellSpacing="2" ForeColor="Black" DataSourceID="SqlDataSource4">
                    <Columns>
                        <asp:BoundField DataField="Nome" HeaderText="Nome" SortExpression="Nome"></asp:BoundField>
                        <asp:BoundField DataField="Morada" HeaderText="Morada" SortExpression="Morada"></asp:BoundField>
                        <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email"></asp:BoundField>
                        <asp:BoundField DataField="DataNasc" HeaderText="DataNasc" SortExpression="DataNasc"></asp:BoundField>
                        <asp:BoundField DataField="Contactos" HeaderText="Contactos" SortExpression="Contactos"></asp:BoundField>
                        <asp:BoundField DataField="Disponibilidade" HeaderText="Disponibilidade" SortExpression="Disponibilidade"></asp:BoundField>
                        <asp:BoundField DataField="Status" HeaderText="Status" SortExpression="Status"></asp:BoundField>
                        <asp:BoundField DataField="Habilitacoes" HeaderText="Habilitacoes" SortExpression="Habilitacoes"></asp:BoundField>
                    </Columns>

                    <FooterStyle BackColor="#CCCCCC"></FooterStyle>

                    <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White"></HeaderStyle>

                    <PagerStyle HorizontalAlign="Left" BackColor="#CCCCCC" ForeColor="Black"></PagerStyle>

                    <RowStyle BackColor="White"></RowStyle>

                    <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White"></SelectedRowStyle>

                    <SortedAscendingCellStyle BackColor="#F1F1F1"></SortedAscendingCellStyle>

                    <SortedAscendingHeaderStyle BackColor="#808080"></SortedAscendingHeaderStyle>

                    <SortedDescendingCellStyle BackColor="#CAC9C9"></SortedDescendingCellStyle>

                    <SortedDescendingHeaderStyle BackColor="#383838"></SortedDescendingHeaderStyle>
                </asp:GridView>



                <asp:SqlDataSource runat="server" ID="SqlDataSource4" DeleteCommand="DELETE FROM Voluntario WHERE IDVoluntario=@IDVoluntario" UpdateCommand="UPDATE Voluntario SET Nome=@Nome, Morada=@Morada, Email=@Email, DataNasc=@DataNasc, Contactos=@Contactos, Disponibilidade=@Disponibilidade, Status=@Status, Habilitacoes=@Hablilitacoes" ConnectionString='<%$ ConnectionStrings:ConnectionString %>' SelectCommand="SELECT [IDVoluntario], [Nome], [Morada], [Email], [DataNasc], [Contactos], [Disponibilidade], [Status], [Habilitacoes] FROM [Voluntario]"></asp:SqlDataSource>
                <asp:GridView ID="gvI" Visible="false" DataKeyNames="IDIdoso" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" runat="server" AutoGenerateColumns="False" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellPadding="4" CellSpacing="2" ForeColor="Black" DataSourceID="SqlDataSource2">
                    <Columns>
                        <asp:BoundField DataField="Nome" HeaderText="Nome" SortExpression="Nome"></asp:BoundField>
                        <asp:BoundField DataField="Morada" HeaderText="Morada" SortExpression="Morada"></asp:BoundField>
                        <asp:BoundField DataField="Contacto" HeaderText="Contacto" SortExpression="Contacto"></asp:BoundField>
                        <asp:BoundField DataField="DataNasc" HeaderText="DataNasc" SortExpression="DataNasc"></asp:BoundField>
                        <asp:BoundField DataField="Condicoes" HeaderText="Condicoes" SortExpression="Condicoes"></asp:BoundField>
                    </Columns>
                    <FooterStyle BackColor="#CCCCCC"></FooterStyle>

                    <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White"></HeaderStyle>

                    <PagerStyle HorizontalAlign="Left" BackColor="#CCCCCC" ForeColor="Black"></PagerStyle>

                    <RowStyle BackColor="White"></RowStyle>

                    <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White"></SelectedRowStyle>

                    <SortedAscendingCellStyle BackColor="#F1F1F1"></SortedAscendingCellStyle>

                    <SortedAscendingHeaderStyle BackColor="#808080"></SortedAscendingHeaderStyle>

                    <SortedDescendingCellStyle BackColor="#CAC9C9"></SortedDescendingCellStyle>

                    <SortedDescendingHeaderStyle BackColor="#383838"></SortedDescendingHeaderStyle>
                </asp:GridView>

                <asp:SqlDataSource runat="server" ID="SqlDataSource2" UpdateCommand="UPDATE Idoso SET Nome=@Nome, Morada=@Morada, Contacto=@Contacto, DataNasc=@DataNasc, Condicoes=@Condicoes" DeleteCommand="DELETE FROM Idoso WHERE IDIDoso=@IDIdoso" ConnectionString='<%$ ConnectionStrings:ConnectionString %>' SelectCommand="SELECT [IDIdoso], [Nome], [Morada], [Contacto], [DataNasc], [Condicoes] FROM [Idoso]"></asp:SqlDataSource>
            </div>
        </div>
    </div>
</asp:Content>

